In [5]:
import numpy as np

def corr(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    num = np.sum((x - x_mean) * (y - y_mean))
    den = np.sqrt(np.sum((x - x_mean)**2) * np.sum((y - y_mean)**2))

    return num / den

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(corr(x, y))  # Expected output: 1.0

1.0


In [9]:
def corr_matrix(X):
    n_features = X.shape[1]
    mat = np.zeros((n_features, n_features))

    for i in range(n_features):
        for j in range(i, n_features):
            c = corr(X[:, i], X[:, j])
            mat[i][j] = c
            mat[j][i] = c

    return mat

In [11]:
X = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
])

print(corr_matrix(X))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
