In [1]:
import numpy as np

def confusion_matrix(y_true, y_pred):
    labels = sorted(set(y_true) | set(y_pred))  
    label_to_index = {label: i for i, label in enumerate(labels)}
    n = len(labels)

    conf_mat = np.zeros((n, n), dtype=int)

    for yt, yp in zip(y_true, y_pred):
        i = label_to_index[yt]
        j = label_to_index[yp]
        conf_mat[i][j] += 1

    return conf_mat, labels  

In [2]:
y_true = [0, 1, 2, 2, 0]
y_pred = [0, 2, 2, 2, 1]

conf_mat, labels = confusion_matrix(y_true, y_pred)
print("Labels:", labels)
print("Confusion Matrix:\n", conf_mat)

Labels: [0, 1, 2]
Confusion Matrix:
 [[1 1 0]
 [0 0 1]
 [0 0 2]]


In [3]:
def precision(conf_mat, avg=None):
    TP = np.diag(conf_mat)
    FP = np.sum(conf_mat, axis=0) - TP
    with np.errstate(divide='ignore', invalid='ignore'):
        precision_per_class = TP / (TP + FP)
        precision_per_class[np.isnan(precision_per_class)] = 0  

    if avg == 'weighted':
        support = np.sum(conf_mat, axis=1) 
        weighted_precision = np.sum(precision_per_class * support) / np.sum(support)
        return weighted_precision
    elif avg == 'macro':
        return np.mean(precision_per_class) 
    else:
        return precision_per_class

In [4]:
conf_mat = np.array([
    [5, 2],
    [1, 7]
])

print("Per-class precision:", precision(conf_mat))
print("Macro average precision:", precision(conf_mat, avg='macro'))
print("Weighted average precision:", precision(conf_mat, avg='weighted'))

Per-class precision: [0.83333333 0.77777778]
Macro average precision: 0.8055555555555556
Weighted average precision: 0.8037037037037038


In [5]:
def recall(conf_mat, avg=None):
    TP = np.diag(conf_mat)
    FN = np.sum(conf_mat, axis=1) - TP
    with np.errstate(divide='ignore', invalid='ignore'):
        recall_per_class = TP / (TP + FN)
        recall_per_class[np.isnan(recall_per_class)] = 0  # handle 0/0

    if avg == 'weighted':
        support = np.sum(conf_mat, axis=1) 
        weighted_recall = np.sum(recall_per_class * support) / np.sum(support)
        return weighted_recall
    elif avg == 'macro':
        return  np.mean(recall_per_class) 
    else:
        return recall_per_class


In [6]:
print("Per-class recall:", recall(conf_mat))
print("Macro recall:", recall(conf_mat, avg='macro'))
print("Weighted recall:", recall(conf_mat, avg='weighted'))

Per-class recall: [0.71428571 0.875     ]
Macro recall: 0.7946428571428572
Weighted recall: 0.8


In [7]:
def f1_score(precision, recall):
    return (2 * precision * recall) / (precision + recall)

In [8]:
prec = 0.8
rec = 0.6
print(f1_score(prec, rec))  # Output: 0.685714...

0.6857142857142857
